### ISSUE TITLE
What does the time component mean?

### ISSUE THREAD

**Issue by DeepDuke** [UTS-RI/dynamic_object_detection#1]
Does the smallest eigenvector have the 4-th element besides (x,y,z)?

```cpp
 float dynamic_score = abs(smallest_eigenvector(3));
```

**Comment by rFalque** [comment]
Hi DeepDuke; we use the [X,Y,Z,time] information (with time being the 4-th component) of the point neighbourhood and compute the normal of this neighbourhood. In our paper, we argue that the time component of the normal (therefore `abs(smallest_eigenvector(3))`) is representative of how dynamic the point is.

Let me know if I did not reply to your question ;)

**Comment by DeepDuke** [comment]
I got it. Thank you so much!

**Comment by PigletPh** [comment]
@rFalque Hello, the calculation formula for dynamic scores is not shown in the paper. What is the specific formula? Thanks!

**Comment by rFalque** [comment]
@PigletPh, sorry for the late reply, we were focused on the coming IROS deadline. 

The dynamic score is obtained by computing the eigenvalue decomposition of the covariance matrix (defined in Equation 1 in the paper). We get the smallest eigenvector (which corresponds to the normal of the surface) and take the last value (which corresponds to the time component).

The corresponding implementation is defined [there](https://github.com/UTS-RI/dynamic_object_detection/blob/c3f03a12c142f912293904f7ee6f7146b079856e/src/dynamic_detector.cpp#L243) in the code. Let us know if you need more clarification
